# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0003_auto_20170615_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleExpressUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, verbose_name='Google Express email')),
                ('password', models.CharField(max_length=120, verbose_name='Google Express password')),
            ],
        ),
    ]
