# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0004_googleexpressuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='products_bought',
            field=models.SmallIntegerField(default=1, verbose_name='Count of bought goods'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='products_count',
            field=models.SmallIntegerField(default=1, verbose_name='Count of goods'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Product order created'), (2, 'Handling order'), (3, 'Order processed'), (4, 'Order processed with errors'), (5, 'Product is sold out')], default=1, verbose_name='Status of order'),
        ),
    ]
