# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0006_auto_20170616_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='products_available',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Count of bought goods'),
        ),
    ]
