# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0007_auto_20170616_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='orders_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='checkout_app.OrdersFileList', verbose_name='Orders file list instance'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Product order created'), (2, 'Handling order'), (3, 'Order processed'), (4, 'Order processed with errors'), (5, 'Product is sold out'), (6, 'Product order is stopped')], default=1, verbose_name='Status of order'),
        ),
    ]
