# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0009_auto_20170621_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='delivery_time',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Delivery time'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='express_order_id',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Google express order id'),
        ),
    ]
