# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0010_auto_20170703_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Product order is created'), (2, 'Handling order'), (3, 'Order is processed'), (4, 'Order is processed with errors'), (5, 'Product is sold out'), (6, 'Product order is stopped'), (7, 'Address is not valid')], default=1, verbose_name='Status of order'),
        ),
    ]
