# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0011_auto_20170705_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='buyer_phone_number',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Buyer phone number'),
        ),
    ]
